### ISSUE TITLE
RIOXX for theses

### ISSUE THREAD

**Issue by katefoneill** [antleaf/rioxx#11]
Posting on behalf of a UKCorr member:

"I'm not sure how useful RIOXX is for describing theses, so fields like supervisor, degree type etc being included. Not sure if this is within scope, but I wanted to raise the question of whether RIOXX could/should be used for theses and is it really suitable?"

**Comment by geo-mac** [comment]
Just sticking this here as an aide memoire; but we might say that you could re-use `<uketdterms:advisor>` from EThOS rather than coin a new element. This kind of thing would need signposting though, if this was the chosen path.

**Comment by paulwalk** [comment]
The [UKETD_DC application profile](https://www.bl.uk/britishlibrary/~/media/bl/global/services/ethos/documents/ethos%20uketd_dc%20application%20profile%20march%202017.pdf?la=en&hash=CEA51777454F4DE1874F9CC69251CA15) already exists for this
