### ISSUE TITLE
rioxxterms:author versus dc:creator

### ISSUE THREAD

**Issue by geo-mac** [antleaf/rioxx#12]
RIOXX deviates from Dublin Core by using a dedicated field for `rioxxterms:author` instead of `dc:creator`. There were reasons for this approach but it may be worth reflecting on this in light of feedback received from individuals based at research active creative, art and design institutions. Here `dc:creator` is more inclusive of creative works. However, another reason to reflect is also the move towards [CReDiT](https://jats4r.org/credit-taxonomy). 

It may therefore seem appropriate to accommodate an element refinement or attribute for `dc:creator`, which could narrow the scope of creator, perhaps even accommodating aspects of CReDiT. This would better treat all disciplines and not just art and design practitioners or academics. For example....
```
<dc:title>RCUK RIOXX Application Profile Version 2.0 Final"</dc:title>
<dc:creator id="https://some-uri/1234" typeIdentifier="https://dictionary.casrai.org/Contributor_Roles/Writing_original_draft" >Paul Walk</dc:creator>
```
Or....
```
<dc:title>Mona Lisa</dc:title>
<dc:creator id="https://www.wikidata.org/wiki/Q762" typeIdentifier="https://www.wikidata.org/wiki/Q483501" >Leonardo di ser Piero da Vinci</dc:creator>

```
Or some such other approach. Personally, I prefer a hierarchical approach in order to be cleaner and satisfactorily structured but I am conscious that this would disrupt what is essentially a flat schema, hence the multiple attributes. Incidentally, [OpenAIRE v4](https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_creator.html#dci-creator) for the first time uses a richer hierarchical approach for `dc:creator` (which has now been supplanted by `datacite:creators`). Anyway, all of the above is merely food for thought and something for discussion.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
