### ISSUE TITLE
Should ISSNs be preferred in URL form?

### ISSUE THREAD

**Issue by paulwalk** [antleaf/rioxx#19]
Where an ISSN has been entered as a `source` property, should this be expressed in URI form?

For example, the ISSN `2304-6775` could be represented as:

`https://portal.issn.org/resource/ISSN/2304-6775`

**Comment by paulwalk** [comment]
I have not been able to find much evidence of ISSNs represented in URI form, and a there is a large amount of use of ISSNs in simple form, so I propose that we accept the common approach of using the simple form.

**Comment by geo-mac** [comment]
I don't have a strong opinion on this yet. I think I suggested it as a possible improvement after noting the ISSN organization have been promoting their ISSN-L ('Linking ISSNs'). Like you, I haven't observed extensive use within digital libraries, repositories, etc. but have noticed ORCID have started using them ('Part of ISSN....'). [See example here.](https://orcid.org/0000-0002-4432-9081) 

![image](https://user-images.githubusercontent.com/15779066/121500747-7f3fbd00-c9d6-11eb-91b7-79014122345a.png)

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
