### ISSUE TITLE
Update to rioxxterms:type

### ISSUE THREAD

**Issue by geo-mac** [antleaf/rioxx#25]
In light of the publication of[ COAR Type Vocabulary v3](https://www.coar-repositories.org/news-updates/resource-types-vocabulary-v3-0/), a minor update to the wording of rioxxterms:type is required -- currently it specifies v2. This was a silly oversight since v3 was heavily trailed.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
