### ISSUE TITLE
Are related resources described by the other elements in the record?

### ISSUE THREAD

**Issue by ThomBlakeLib** [antleaf/rioxx#26]
Not actually an issue just a clarification for me. If the _dc:identifier_ element is pointing to a repository splash page, and there are a number of related documents linked to using _dc:relation_ (which seems a good solution by the way), is the idea that other elements in the record like _rioxxterms:author_, _rioxxterms:version_, _ali:license_ref_ etc will extend to apply to all the related resources given in _dc:relation_?

**Comment by paulwalk** [comment]
No, the idea is that the RIOXX record's properties apply to the "thing" identified in the `dc:identifier` property. I would expect the common case to be that the related resources are very closely related to the main resource.

**Comment by ThomBlakeLib** [comment]
Ah, ok. So related resources would usually each have their own RIOXX record?

**Comment by paulwalk** [comment]
That's a policy matter for the repository. I think the common case is to think of this in roughly FRBR terms - the RIOXX record describes the "work" which has a canonical URL (the repository splash page) and has related "expressions" in terms of, for example, the PDF for a preprint which we reference in the RIOXX record using the `dc:relation` property.

**Comment by ThomBlakeLib** [comment]
Thanks Paul, and sorry for a slow reply. When I read it I was initially thinking sort of along the lines of a "work" (although FRBR is a really useful point of reference, so thanks for that.) That was what got me thinking about how some of the properties apply. `rioxxterms:version` and `ali:license_ref` in particular seem to make most sense if they apply at the "expresions" level - so in your example to the actual PDF of the preprint. I'm less sure how these would work at the level of the work.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
