### ISSUE TITLE
Reasons for removing the <rioxxterms:apc> property in v3 draft?

### ISSUE THREAD

**Issue by JonathanJEaton** [antleaf/rioxx#28]
Hello,

Not an issue, rather a question: what are the reasons behind removing the <rioxxterms:apc> property?

**Comment by geo-mac** [comment]
There might be a fuller explanation somewhere in the [governance group minutes](https://www.rioxx.net/governance/) but, from recollection, an important reason was simply that its original inclusion was at the insistence of the old RCUK, for the purposes of financial monitoring. But in the end they didn't use it, let alone RIOXX itself. It was concluded that the updated use cases for RIOXX do not require it and, as things are, I don't think it would be accommodated under the current data model.

**Comment by JonathanJEaton** [comment]
Thanks for your reply and advice.  We've used it extensively in our EPrints for tracking our very sporadic APCs.  (We're a "small" graduate institution and don't benefit from the kinds of block grants given to other HEIs.)  But like other libraries, we're now moving towards wider TA adoption for key publishers, to transform our OA workflows from default (embargoed) Green, to immediate free-to-read where possible. 

So using the Rioxx2 profile options to record an APC event in-line with the metadata and free-to-read deposit record, was mighty helpful for internal reporting.  However, as Jisc Monitor Local is now working on adding TA support, after Rioxx3 release we can move our tracking over.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
