### ISSUE TITLE
dc:publisher - uri limited to ISNI

### ISSUE THREAD

**Issue by jesusbagpuss** [antleaf/rioxx#30]
The definition for the `<dc:publisher>` elements allows a `uri` attribute, but this is limited to ISNIs.

The descrition states:
> This could be a person, organisation or service. 

Why is the `uri` attribute limited to ISNIs?
Should _any_ recognised PID (stated in an HTTP(S) form) be acceptable?

IMHO, _any_ PID would be better than _no ISNI_!

**Comment by geo-mac** [comment]
> Should any recognised PID (stated in an HTTP(S) form) be acceptable?

Yes, it should! :-) Thanks for highlighting. This is an oversight -- and probably my fault. Doh! A final version of RIOXX 3.0 is soon to be published tho, and in this version any recognised PiD will be the expectation.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
