### ISSUE TITLE
Add rioxxterms:fulltext_deposit_date

### ISSUE THREAD

**Issue by petrknoth** [antleaf/rioxx#4]
I propose to add a new field to the rioxxterms vocabulary. 

Name: rioxxterms:fulltext_deposit_date
Cardinality: Zero or one
Description: full text deposit date is the first date when the record is a) live in the repository and b) has the Accepted or Published version of the full text manuscript attached. Note that while the full text might still be under embargo at this time, it must have been deposited.  

The field takes a date value which MUST be encoded using ISO 8601 (post–2004 versions) which follows the following format: YYYY-MM-DD.

Rationale: The field has a wide range of applications with the primary one being the ability to check compliance with the OA REF2021 policy. 
Relevant references: 
- Herrmannova, Drahomira; Pontika, Nancy and Knoth, Petr (2019). Do Authors Deposit on Time? Tracking
Open Access Policy Compliance. In: 2019 ACM/IEEE Joint Conference on Digital Libraries, 2-6 Jun 2019, UrbanaChampaign, IL, http://oro.open.ac.uk/60478/1/JCDL_2019____REF_Compliance.pdf
- CORE support for UK HEIs in the REF 2021 Open Access Audit: https://core.ac.uk/ref-audit/

**Comment by geo-mac** [comment]
I agree this could be useful and an easy date to capture; but I think the motivation for its inclusion probably has to be articulated from outside a REF2021 mind-set. By that I mean that the inclusion of new elements should fulfill a variety of use-cases and not be primarily driven by local policy compliance considerations.

@petrknoth So, what was your thinking RE the wide range of applications? I can think of some use-cases along a CORE Discovery or Unpaywall line - but, without rumination time at the moment, I can't think of others. I need more coffee! :-)

**Comment by petrknoth** [comment]
I think that some of the very key applications here include:
- Being able to monitor the uptake of open access, i.e. growth of full text articles in repositories over time
- Being able to measure the speed of deposition of articles into repositories (deposition time lag). This is (and will be) important for a number of OA policies and the success of the OA movement more broadly. As researchers tend to read more recent articles, it is important that we not only have a large proportion of papers OA, but that we have "fast OA", i.e. recent articles available as OA.   See the two references above.
- repository registries, such as OpenDOAR, would benefit as well as they could show historical growth of content in repositories

**Comment by geo-mac** [comment]
Nice one! Yes, this one: 

> measure the speed of deposition of articles into repositories (deposition time lag). 

...was something I imagined as having useful applications within something like, say, the Unpaywall dashboard, e.g. providing intelligence on deposit speed across a number of different indicators such as region, institution type, research area, etc.

**Comment by paulwalk** [comment]
I generally support this, but I’m just wondering about scope. Is it generally accepted that a “pre-print” is an Accepted manuscript?

**Comment by petrknoth** [comment]
> Nice one! Yes, this one:
> 
> > measure the speed of deposition of articles into repositories (deposition time lag).
> 
> ...was something I imagined as having useful applications within something like, say, the Unpaywall dashboard, e.g. providing intelligence on deposit speed across a number of different indicators such as region, institution type, research area, etc.

@geo-mac we are developing this functionality for the future release of the CORE Dashboard (shh). But getting the data is very hard at the moment and this change would significantly simplify the technical workflow and make the provenance of the information more transparent.

**Comment by petrknoth** [comment]
> I generally support this, but I’m just wondering about scope. Is it generally accepted that a “pre-print” is an Accepted manuscript?

@paulwalk I believe that Accepted version should be defined as the file which which was submitted for peer review. If the record concerns an article which is not subject to a peer review, then this field should remain empty.

**Comment by geo-mac** [comment]
> I believe that Accepted version should be defined as the file which which was submitted for peer review. If the record concerns an article which is not subject to a peer review, then this field should remain empty.

@petrknoth @antleaf I think it is important to nail this down the scope here as I think there is a bit of semantic drift! So, for clarity, the following is true:

- **Preprint** = _prior_ to peer review and as submitted for peer review.
- **Accepted (author) manuscript (or post-print)** = manuscript _after_ peer review and with changes resulting from peer review implemented.

There is, of course, a philosophical argument to be had about the intellectual status of preprints but I think @petrknoth is referring to accepted manuscripts and publisher 'version of record (i.e. publisher PDF) **only**. Is that correct? Preprints are out of scope...

**Comment by paulwalk** [comment]
I am quite interested in RIOXX being used to disseminate information about preprints, so I’d like to be very clear about this!

**Comment by geo-mac** [comment]
Good - we're all clear! :-) I think scoping preprints is very sensible indeed, esp. given their recent growth. We simply need to extend @petrknoth 's proposed description to be sufficiently specific about their inclusion.

**Comment by Ainmhidh** [comment]
Just for clarity (for my sake at least) - I presume the plan is to stick with the definitions at https://www.niso.org/sites/default/files/2017-08/RP-8-2008.pdf which are currently encapsulated in RIOXX2,  so the term pre-print is related to AO or SMUR and post-print is AAM onwards?
OBviously different use cases / disciplines will have different ideas about which versions should count as fulltext for the fulltext-deposit-date so clarity on which versions dates are captured is important.

**Comment by paulwalk** [comment]
> so the term pre-print is related to AO or SMUR and post-print is AAM onwards?

I think that's right.

I think that @petrknoth's suggestion at the start of this thread does not cover pre-prints.

**Comment by jesusbagpuss** [comment]
Just discussing this with colleagues - back to the first few posts in this issue - the term 'deposit' has become overloaded.

Deposit (when an author provides a version of the paper to the repository)
and
Deposit (when an item is available from the repository)
are two very different things (unless you don't have a mediated workflow in the repo).

REF reckoning is based on the first of these.
CORE currently picks up the second of these via RIOXX in most cases - as most repos don't present the first date anywhere, and cannot currently represent the first date in RIOXX.

I'm happy to have this element, but it would need to be clearly defined, and the REF definition would need to be erased from a lot of people's minds...

If there is a longer-term need to say "the creator has done everything they need to on date X" and "the mediator has done everything on date Y" then we need two fields.

**Comment by geo-mac** [comment]
Just picking this up as a little aide memoire for governance purposes in order to note that the distinction made by @jesusbagpuss is made in the REF CC plugin for Eprints and REF compliance checker for DSpace, with first compliant deposit (FCD) & first compliant Open Access (FOA) existing as separate elements. Data are of course captured automatically by the system. 

It does all point to the need for two fields in RIOXX in order to satisfy this requirement soundly. Say,
```
rioxxterms:fulltext_deposit_date
rioxxterms:fulltext_exposed_date
```
...each precisely defined. These definitions would be cognate with FCD and FOA allowing reuse in other applications or vice versa.

**Comment by petrknoth** [comment]
Thank @geo-mac . I agree with you. This suggests that we should keep rioxxterms:fulltext_deposit_date and  additionally create another thread about rioxxterms:fulltext_exposed_date.

**Comment by paulwalk** [comment]
rioxxterms:fulltext_deposit_date has been added to the new draft profile
