### ISSUE TITLE
Cardinality of Grant/ Project information

### ISSUE THREAD

**Issue by ajtag** [antleaf/rioxx#45]
Grant and Project tags, both have a cardinality of one or more, with the content of the tag requiring PIDs for the related grant or project.  Requiring a valid metadata record to have a project and grant identifiers.

As it quite possible, this information isnt available should the cardinality be zero or more?

checking records from eprints to see how this is handled in the wild, it looks like it takes the zero or more approach:
https://eprints.gla.ac.uk/cgi/oai2?verb=GetRecord&identifier=oai:eprints.gla.ac.uk:279631&metadataPrefix=rioxx
https://eprints.whiterose.ac.uk/cgi/export/eprint/109996/RIOXX2CC0/wrro-eprint-109996.xml

In considering the change from V2 -> V3RC1 Project information has been split out into grant/ project so I am assuming the cardinality has been carried over? and suggest both fields should be zero or more.

**Comment by geo-mac** [comment]
>  both fields should be zero or more.

Well spotted. I suspect this is simply a typo which has evaded review, so thanks for spotting. :-) Yes, it should be zero or more for both rioxxterms:grant and rioxxterms:project. 

Modelling around grants, projects and funders has suffered from a lot of semantic conflation over recent years. Separating grants and projects was therefore to necessary to fix this conflation in Rioxx. It's an issue in OpenAIRE too and needs to be addressed in a future release.

**Comment by paulwalk** [comment]
Yes - that looks like a typo to me - thanks for reporting this.

**Comment by geo-mac** [comment]
Issue fixed in #48 and #49.
