### ISSUE TITLE
Specifying access rights at file level

### ISSUE THREAD

**Issue by geo-mac** [antleaf/rioxx#47]
_Documenting an offline discussion here for consideration by the Rioxx Governance Group._ 

Specifying access rights via a number of approaches has been considered by the RGG on numerous occasions. These discussions have centred on root vs file level access rights. It may be worth considering a re-visitation of access rights specified at file level within `dc:relation` using, for example, an accessRightsURI attribute containing a value from the [COAR vocabulary](https://vocabularies.coar-repositories.org/access_rights/).

This might be communicated as follows:

```
<dc:relation type="https://schema.org/ScholarlyArticle" deposit_date="2021-07-06" resource_exposed_date="2021-07-20" accessRightsURI="http://purl.org/coar/access_right/c_abf2">
    https://www.repository.org/article_123456_preprint.pdf
</dc:relation>
```

Nice. But potential issues with this approach:

1. Asserting metadata properties about resources that are not necessarily under institutional control, which is potentially an issue for those wishing to encode associative relationships with other resources (e.g. for the purposes of discovery, PID graph, etc.). Can institutions be certain of the access rights?
2. There are certain access rights that can be inferred without such an attribute. For example, `resource_exposed_date`, pre-expiration, infers 'embargoed'; `resource_exposed_date` post-expiration infers 'open'.
3. It is conceivable that access rights for 3rd party resources (encoded for the purposes of discovery, the PID graph, and so forth...) may change over time, resulting in metadata obsolesce. Related to issue #1 above, essentially.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
