### ISSUE TITLE
Add rioxxterms:record_public_release_date

### ISSUE THREAD

**Issue by petrknoth** [antleaf/rioxx#5]
I propose to add a new field to the rioxxterms vocabulary.

Name: rioxxterms:record_public_release_date
Cardinality: Exactly one
Description: Record public release date is the first date when the record went live in the repository. The field is mandatory. 

The field takes a date value which MUST be encoded using ISO 8601 (post–2004 versions) which follows the following format: YYYY-MM-DD.

Rationale: The field has a wide range of applications the key one being able to track the historical growth of content within repositories. Note: ideally, this field would be created at an even more general level than rioxxterms.

**Comment by paulwalk** [comment]
This seems reasonable.

Refarding:
> Note: ideally, this field would be created at an even more general level than rioxxterms.

I don't think this is an issue. Terms in the rioxxterms namespace are open for anyone to use in any other application profile or schema. It is easier to define and manage this new term here in this namespace, and then invite others to use it.

**Comment by petrknoth** [comment]
I agree with you Paul. Thanks.

**Comment by ThomBlakeLib** [comment]
Agree that this would be a good addition, but...

> The field has a wide range of applications the key one being able to track the historical growth of content within repositories.

I think it would be incorrect to assume that the presence of a record is in itself indicative of any content beyond the record itself.

**Comment by paulwalk** [comment]
@ThomBlakeLib yes - agreed. @petrknoth - can you clarify - you mean for this date to apply to when a metadata record was first ‘published’ in the repo, and that it has nothing to do with any content ‘described’ by that metadata record?

**Comment by petrknoth** [comment]
@ThomBlakeLib @paulwalk Yes, this has nothing to do with the content. This is only referring to the public release date of the record itself.

**Comment by paulwalk** [comment]
this property has been included in the new draft profile
