### ISSUE TITLE
Documenting thinking about #46

### ISSUE THREAD

**Issue by geo-mac** [antleaf/rioxx#53]
Documenting related thinking surrounding issue #46 .

There was [an RGG action to audit Rioxx properties](https://www.rioxx.net/governance/minutes/2022-11-07/) which might usefully be contained within `dc:relation` in order to better describe related but actionable resources. This might typically be other 'expressions' of the same resource. Properties that might be relevant to the description of expressions include:

`rioxxterms:type` (already accommodated within dc:relation via type= schema.org attribute)
`rioxxterms:version`
`dc:format`

In addition, the following properties are peripherally relevant but present issues:

`dc:coverage`
`ali:license`

If we are strict about this, `dc:coverage` should be included within `dc:relation` expressions since its scope under DCMI is so broad. But based on typical repository usage we could be inclined to argue that it would be low risk to exclude it from related expressions and instead retain it at the root level. 

How should `ali:license` be treated? Inclusion of `ali:license` rubs up against intended adoption of `accessRightsURI` within `dc:relation` instances -- but with actual license conditions remaining unexpressed in `dc:relation` instances. Does it make sense for `ali:license` to remain at root level to describe the `rioxxterms:version_of_record`, with separate rights information communicated for expressions via attribute? Probably not since this could open up potential contradiction -- so perhaps an alternative approach to expressing rights is necessary across root and expression levels? This aspect requires further thought (comments below, please!). Leaving this specific question aside for now, but acknowledging everything else, we might expect expressions to be expressed somewhat as follows:

```xml
<dc:relation type="https://schema.org/ScholarlyArticle" 
    deposit_date="2021-07-28" 
    resource_exposed_date="2021-07-28" 
    accessRightsURI="http://purl.org/coar/access_right/c_abf2" 
    rioxx_version="http://purl.org/coar/version/c_ab4af688f83e57aa" 
    format="application/pdf">
            https://www.repository.org/article_1234567.pdf
</dc:relation>
```

An obvious question arises around the heavy use of XML attributes to compensate for a lack of hierarchical inheritance. Should we be in the business of worrying about this...?

Possible internal contradiction insofar as schema.org is used for `type` within `dc:relation` but COAR vocabulary used for `rioxxterms:type`.

**Comment by ajtag** [comment]
I would like to add a note to your thinking, and document a recent experience:

If licences apply to documents rather than the work, there will be an impact on the following statement as well.

From rioxxterms:publication_date:
> As Rioxx can be used to help establish compliance with funders' mandates and licensing of open access publications, the critical dates for the assertion of compliance are those held in the start_date attributes of the ali:license_ref properties.

I am assuming, those comments refer to a recent case where the wording was

> Date of publication' means the date that the final 'version of record' is first made publicly available.

however this did not align with the rioxx v2 spec where

rioxxterms:publication_date: 
> This element takes the publication date of the resource in the form in which it would be cited. 

having dates associacted with the version would have helped in that case.


The publication date associated with a related document and the COAR vocab for version could have helped in that case.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
