### ISSUE TITLE
Incorrect documentation: https://www.rioxx.net/schema/v3.0/rioxxterms/ (needs updating to v3)

### ISSUE THREAD

**Issue by jesusbagpuss** [antleaf/rioxx#68]
I've just been thoroughly confusing myself with the RIOXX website. 
In short:
- OK: https://www.rioxx.net/schema/v3.0/rioxx/rioxx.xsd (links to below)
- OK: https://www.rioxx.net/schema/v3.0/rioxx/rioxxterms.xsd
- OK: https://www.rioxx.net/schema/v3.0/rioxx/ (documentation)
- BAD: https://www.rioxx.net/schema/v3.0/rioxxterms/ (documentation) 

The rioxx3.xsd schema presented on the RIOXX website links to the following for the rioxxterms namespace:
https://rioxx.net/schema/v3.0/rioxxterms/

That file has an updated namespace at the top, linking it to v3, but the documentation (and content) of the xsd appear to be for v2.

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.rioxx.net/schema/v3.0/rioxxterms/"
    xmlns:rioxxterms="http://www.rioxx.net/schema/v3.0/rioxxterms/"
    xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
    <xs:annotation>
        <xs:documentation xml:lang="en"><![CDATA[
Schema for the RIOXX Terms used within the RIOXX Application Profile, version 2.0

Created 2015-01-21
```

**Comment by paulwalk** [comment]
Thanks for the report - I have asked the author of the schema XSDs to take a look.

**Comment by paulwalk** [comment]
Fixed and pushed to live system. Thanks for reporting @jesusbagpuss - and thanks for fixing @mcancellieri!
