### ISSUE TITLE
Improve website: list of properties and table of properties/example should be sorted the same

### ISSUE THREAD

**Issue by jesusbagpuss** [antleaf/rioxx#69]
The website would be more usable/make better sense if these were in the same order.
The list of properties is sorted:
https://github.com/antleaf/rioxx/blob/949a06174401a08421c5ba729d85064114d4999c/webroot/themes/rioxx/layouts/profiles/single.html#L10-L13

but the corresponding table isn't:
https://github.com/antleaf/rioxx/blob/949a06174401a08421c5ba729d85064114d4999c/webroot/themes/rioxx/layouts/profiles/single.html#L29-L37

**Comment by paulwalk** [comment]
Thanks @jesusbagpuss - I completely agree with your suggestion about the sort order and have fixed this now. Thanks for reporting and for suggesting the correct fix!
