### ISSUE TITLE
Alignment between rioxxterms:type and http://vocabularies.coar-repositories.org/documentation/resource_types/

### ISSUE THREAD

**Issue by bram-atmire** [antleaf/rioxx#7]
Disclaimer: just writing this feedback from a very personal perspective, not with an Atmire or DSpace Committer hat on.

I love the simplicity and relevance of the rioxxterms:type vocabulary, compared to the more exhaustive, hierarchical vocabulary of the new COAR vocabulary.

I hope that everyone would agree that it would be a good thing if there would be a clear, unambiguous mapping between the two, as the basis for alignment.

For that purpose, I'm proposing the following:

1. Drop "Book edited". As this makes an implication about the contributor ship of the institution or one of the authors.
2. Rename "Conference Paper/Proceeding/Abstract" to Conference Object
3. Either rename "Journal Article/Review" to "contribution to journal" or split it up into "journal article" and "review article".
4. Rename "Manual/Guide" to "Technical Documentation"
5. Drop Monograph, duplicate for book
6. Rename "Policy briefing report" to "Policy Report"
7. Make a case for the introduction of Technical Standard into the COAR vocabulary
8. Either drop "Consultancy Report" or rename into one of the report categories of the COAR vocabulary.

If these 8 things would be resolved, there would be an unambiguous mapping.

**Comment by geo-mac** [comment]
Nice one, Bram. Interestingly there are already mappings as part of an [EPrints plugin](http://bazaar.eprints.org/422/), which maps EPrints types to COAR v.1. An alternative starting point? In some areas the EPrints default schema demonstrates higher levels of specificity (see snippet below from EPrints config file (.pl), although I notice COAR v.2 has expanded the type vocabulary. 

There must be a story behind the original controlled list in RIOXX. Initially I thought it was simply derived from the [DCMI Type Vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-type-vocabulary/2003-02-12/) but, upon revisiting the DCMI, I was surprised at how limited it really is. This may explain the separate list, especially as COAR v.1 actually predated RIOXX. 

```
	'article' => 'c_6501', #journal article
	'book_section' => 'c_3248', #book part
	'monograph' => '', #use monograph_type to decide 
	'conference_item' => 'c_c94f', #conference object
	'book' => 'c_2f33', #book
	'thesis' => 'c_46ec', #thesis
	'patent' => 'c_15cd', #patent
	'artefact' => 'c_1843', #other
	'exhibition' => 'c_1843', #other
	'composition' => 'c_18cd', #musical composition
	'performance' => 'c_1843', #other
	'image' => 'c_ecc8', #still image
	'video' => 'c_12ce', #video
	'audio' => 'c_18cc', #sound
	'dataset' => 'c_ddb1', #dataset
	'experiment' => 'c_1843', #other
	'teaching_resource' => 'c_1843', #other
	'other' => 'c_1843', #other
'technical_report' => 'c_18gh', #technical report
	'project_report' => 'c_18op', #project deliverable
	'documentation' => 'c_71bd', #technical documentation
	'manual' => 'c_71bd', #technical documentation
	'working_paper' => 'c_8042', #working paper
	'discussion_paper' => 'c_8042', #working paper
	'other' => 'c_18wq', #other type of report
```

**Comment by paulwalk** [comment]
Very simply, the `rioxxterms:type` vocabulary was decided by an RCUK Committee. As one of the two authors of RIOXX, I had no influence over this at the time as RIOXX was originally developed for RCUK.

Now we have an opportunity to revise this vocabulary. At first glance, I like @bram-atmire‘s suggestions. Making a clear mapping to the COAR vocab is something I would strongly support too.

**Comment by geo-mac** [comment]
Just sticking a pin in something J.Smith (SGUL) raised via UKCORR in relation to 'conference object' interpretations which emerged from the UK REF. See p.105 of the [Guidance on Submissions](https://www.ref.ac.uk/media/1089/ref-2019_01-guidance-on-submissions.docx). (large Word doc).

COAR v.2 accommodates the following types:

 conference object
    -- conference proceedings
        -- conference paper
        -- conference poster
    -- conference paper not in proceedings
    -- conference poster not in proceedings

...which is quite comprehensive without being overly specific, IMHO. But the definitions in REF appear more specific. Though RIOXX isn't so much about REF, it may form a useful reference point if the RIOXX type vocabulary is revised and mappings to COAR v.2 are pursued.

Anyway, just recording here as an aide memoire!

**Comment by geo-mac** [comment]
A further note following some recent requirements elicitation, COAR v.2 features better treatment of resources generally (great!), but it does not appear to adequately addresses research types emanting from the creative, art and design domains. Might it be necessary to accommodate an alternative type vocabulary? Such an alternative does not appear forthcoming. My understanding that attempts to move this forward have failed – although, as some might be aware, [KULTUR project](http://kultur.eprints.org/about.htm) did propose some which could be reused in conjunction with COAR.

I reached out to the [COAR Controlled Vocabularies Interest Group](http://vocabularies.coar-repositories.org/documentation/resource_types/) to ask about this and according to Jochen Schirrwagen they are considering its extension.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
