### ISSUE TITLE
Concerns about rioxxterms:version values

### ISSUE THREAD

**Issue by geo-mac** [antleaf/rioxx#8]
_Some interested parties are uncomfortable using GitHub and have therefore contacted me by email. I am therefore posting this particular issue on behalf of a UKCORR member and documenting it as an aide memoire for subsequent discussions._

Concerns have been expressed about used of the JAV vocabulary for rioxxterms:version. JAV includes the following values:

- AO = Author's Original
- SMUR = Submitted Manuscript Under Review
- AM = Accepted Manuscript
- P = Proof
- VoR = Version of Record
- CVoR = Corrected Version of Record
- EVoR = Enhanced Version of Record
- NA = Not Applicable (or Unknown)

Despite JAV being published in 2008 - and despite including [numerous publishers on its working group](https://www.niso.org/standards-committees/journal-article-versions) - there are concerns that it lacks currency in scholarly publishing circles. This member states:

> It is not clear that the category list is understood or being used by publishers.  Hence, defaulting to NA for not applicable or unknown (or making a best guess) will be necessary, at least initially.  Further definition and common application of the category types is essential if this information is to be collected properly and be of value.

Similar concerns have been noted in the literature and has never been adopted (?) by CrossRef et al.

Apart from documenting this here, my question (writing as @geo-mac now!) is: are there really any alternatives? OpenAIRE v4 is using JAV for oaire:version too and it is essentially used as the basis for the COAR vocabulary version types.

**Comment by geo-mac** [comment]
Btw, another aspect to 'stick a pin in' is non-traditional scholarly works, e.g. content that does not conform to the scholarly publication paradigm of a 'journal article'.  Been contacted by a number of members who flag the exclusionary nature of profile from this perspective....

**Comment by bram-atmire** [comment]
I can't think of any examples of non-traditional scholarly works where "Author's Original (AO)" would be inappropriate. Do you have any examples?

That said, my personal +1 on aligning with OpenAIRE/COAR on the use of JAV.

* https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_resourceversion.html
* http://vocabularies.coar-repositories.org/documentation/version_types/

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
